server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.zy.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

# spring
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cloudstudy?useUnicode=true&characterEncoding=UTF-8

# Eureka单机的配置
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
    instance:
      instance-id: springcloud-provider-8001

# Eureka集群的配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/，http://eureka7002.com:7002/eureka/，http://eureka7003.com:7003/eureka/
#    instance:
#      instance-id: springcloud-provider-8001

# actuator监控配置
info:
  app.name: zy-springcloud-study
  company.name: zyuan